pipeline {
agent any

tools{
maven "MAVEN_HOME"
}



stages {

stage("Checkout code"){
steps
{
checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'utkarsh.dixit@nagarro.com', url: 'https://git.nagarro.com/GITG00641/Java/utkarsh-dixit.git']]])

echo 'Check Out'
}
}
stage('Clean') {
steps {
bat 'mvn -f LibraryManagementSystem/ADVANCE_JAVA_ASS_5_1ST/pom.xml clean'
echo 'Cleaning..'
}
}
stage('Compile') {
steps {
bat 'mvn -f LibraryManagementSystem/ADVANCE_JAVA_ASS_5_1ST/pom.xml compile'
echo 'Compiling..'
}
}
stage('Test') {
steps {
bat 'mvn -f LibraryManagementSystem/ADVANCE_JAVA_ASS_5_1ST/pom.xml test'
echo 'Testing..'
}
}
stage('Packaging') {
steps {
bat 'mvn -f LibraryManagementSystem/ADVANCE_JAVA_ASS_5_1ST/pom.xml package'
echo 'Packageing..'
}
}
stage('Install') {
steps {
bat 'mvn -f LibraryManagementSystem/ADVANCE_JAVA_ASS_5_1ST/pom.xml install'
echo 'Installing..'
}
}
stage('SonarQube analysis') {
    steps {
      bat 'mvn -f LibraryManagementSystem/ADVANCE_JAVA_ASS_5_1ST/pom.xml clean verify sonar:sonar -Dsonar.projectKey=frontend -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_62ddbea5d955054c49b4348bcd5e6da1770394ca'
  echo 'sonarqube code analysys..'
}

}
}
}
